pipeline {
    agent any

    stages {

        stage('Checkout Code') {
            steps {
                git credentialsId: 'github-token',
                    url: 'https://github.com/khandareSwwapnil/Management.git',
                    branch: 'main'
            }
        }

        stage('Backend Build & Test') {
            steps {
                dir('Hostel Web') {
                    bat 'mvn clean package'
                }
            }
        }
    }
}