pipeline {
    agent any

    tools {
        jdk 'JDK17'
        maven 'Maven3'
        // ❌ nodejs removed
    }

    environment {
        GIT_CREDENTIALS = 'github-token'
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/khandareSwwapnil/Hostel-Management-System-.git'
            }
        }

        stage('Backend Build & Test') {
            steps {
                bat 'mvn clean test package'
            }
        }

        stage('Archive Artifacts') {
            steps {
                archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
            }
        }
    }

    post {
        success {
            echo "✅ BUILD SUCCESS"
        }
        failure {
            echo "❌ BUILD FAILED"
        }
        always {
            cleanWs()
        }
    }
}