pipeline {
    agent any

    stages {

        stage('Checkout Code') {
            steps {
                git credentialsId: 'github-token',
                    url: 'https://github.com/khandareSwwapnil/Management.git',
                    branch: 'main'
            }
        }

        stage('Check Java') {
            steps {
                bat 'java -version'
                bat 'echo %JAVA_HOME%'
            }
        }

        stage('Build Backend') {
            steps {
                dir('Hostel Web') {
                    bat 'mvn clean package'
                }
            }
        }

        stage('Archive Artifacts') {
            steps {
                dir('Hostel Web') {
                    archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
                }
            }
        }

        stage('Run Application (Local Deploy)') {
            steps {
                dir('Hostel Web') {
                    bat 'start java -jar target/*.jar'
                }
            }
        }
    }

    post {
        success {
            echo '✅ BUILD SUCCESS'
        }
        failure {
            echo '❌ BUILD FAILED'
        }
    }
}