spring.application.name=HMS
spring.datasource.url=jdbc:postgresql://localhost:5432/HMS_Data
spring.datasource.username=postgres
spring.datasource.password=Swapnil
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.port=8081

spring.main.allow-bean-definition-overriding=true

spring.datasource.driver-class-name=org.postgresql.Driver


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=swapnilkhandare978@gmail.com
spring.mail.password=qdbqixaivrpmleol

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.debug=true

