spring.application.name=HMS
spring.datasource.url=jdbc:postgresql://localhost:5432/HMS_Data
spring.datasource.username=postgres
spring.datasource.password=Swapnil
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto= update
server.port=8081
spring.datasource.driver-class-name=org.postgresql.Driver


spring.boot.admin.client.uri = http://localhost:8080
management.endpoints.web.exposure.include=*
management.endpoints.health.show-details = always




management.endpoints.logfile,enabled = true